### ISSUE TITLE
'charmap' codec can't decode byte 0x98

### ISSUE THREAD

**Issue by SuperZombi** [SuperZombi/MyTube#1]
```
'charmap' codec can't decode byte 0x98 in position 47: character maps to <undefined>
```

```
Traceback (most recent call last):
File "main.py", line 129, in handler
File "asyncio\runners.py", line 190, in run
File "asyncio\runners.py", line 118, in run
File "asyncio\base_events.py", line 653, in run_until_complete
File "MyTube\downloader.py", line 81, in __call__
File "MyTube\downloader.py", line 119, in _mix
File "MyTube\downloader.py", line 183, in _ffmpeg
File "encodings\cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 47: character maps to <undefined>
```
Downloader 183:
```python
subprocess.Popen([self.FFMPEG, "-hide_banner"] + command, encoding=os.device_encoding(0), universal_newlines=True, startupinfo=self.startupinfo, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
```

**Comment by SuperZombi** [comment]
Changed it to `encoding='utf-8'`.
